version: '3.8'
services:
  app:
    image: your_image_name
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - my_database_volume:/Odinochka/Odinochka_fl/instance/
volumes:
  my_database_volume:
     